# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anonimizacion.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'anonimizacion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61nonimizacion.proto\x12\ranonimizacion\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n\x0e\x44\x61tosSensibles\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x18\n\x10\x66\x65\x63ha_nacimiento\x18\x02 \x01(\t\x12\x11\n\tdireccion\x18\x03 \x01(\t\x12\x14\n\x0c\x64ocumento_id\x18\x04 \x01(\t\"Q\n\x0fTipoInformacion\x12\x11\n\tmodalidad\x18\x01 \x01(\t\x12\x18\n\x10region_anatomica\x18\x02 \x01(\t\x12\x11\n\tpatologia\x18\x03 \x01(\t\"\xda\x01\n\rAnonimizacion\x12\x18\n\x10\x61nonimizacion_id\x18\x01 \x01(\t\x12\x36\n\x0f\x64\x61tos_sensibles\x18\x02 \x01(\x0b\x32\x1d.anonimizacion.DatosSensibles\x12\x38\n\x10tipo_informacion\x18\x03 \x01(\x0b\x32\x1e.anonimizacion.TipoInformacion\x12\x0e\n\x06imagen\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\".\n\x12QueryAnonimizacion\x12\x18\n\x10\x61nonimizacion_id\x18\x01 \x01(\t\"u\n\x16RespuestaAnonimizacion\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x38\n\ranonimizacion\x18\x02 \x01(\x0b\x32\x1c.anonimizacion.AnonimizacionH\x00\x88\x01\x01\x42\x10\n\x0e_anonimizacion2\xd9\x01\n\x14\x41nonimizacionService\x12[\n\x12\x43rearAnonimizacion\x12\x1c.anonimizacion.Anonimizacion\x1a%.anonimizacion.RespuestaAnonimizacion\"\x00\x12\x64\n\x16\x43onsultarAnonimizacion\x12!.anonimizacion.QueryAnonimizacion\x1a%.anonimizacion.RespuestaAnonimizacion\"\x00\x42\x37\n\x18\x63o.edu.uniandes.misw4406B\x12\x41nonimizacionProtoP\x01\xa2\x02\x04\x41NONb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anonimizacion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030co.edu.uniandes.misw4406B\022AnonimizacionProtoP\001\242\002\004ANON'
  _globals['_DATOSSENSIBLES']._serialized_start=71
  _globals['_DATOSSENSIBLES']._serialized_end=170
  _globals['_TIPOINFORMACION']._serialized_start=172
  _globals['_TIPOINFORMACION']._serialized_end=253
  _globals['_ANONIMIZACION']._serialized_start=256
  _globals['_ANONIMIZACION']._serialized_end=474
  _globals['_QUERYANONIMIZACION']._serialized_start=476
  _globals['_QUERYANONIMIZACION']._serialized_end=522
  _globals['_RESPUESTAANONIMIZACION']._serialized_start=524
  _globals['_RESPUESTAANONIMIZACION']._serialized_end=641
  _globals['_ANONIMIZACIONSERVICE']._serialized_start=644
  _globals['_ANONIMIZACIONSERVICE']._serialized_end=861
# @@protoc_insertion_point(module_scope)
