# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import anonimizacion_pb2 as anonimizacion__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in anonimizacion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnonimizacionServiceStub(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearAnonimizacion = channel.unary_unary(
                '/anonimizacion.AnonimizacionService/CrearAnonimizacion',
                request_serializer=anonimizacion__pb2.Anonimizacion.SerializeToString,
                response_deserializer=anonimizacion__pb2.RespuestaAnonimizacion.FromString,
                _registered_method=True)
        self.ConsultarAnonimizacion = channel.unary_unary(
                '/anonimizacion.AnonimizacionService/ConsultarAnonimizacion',
                request_serializer=anonimizacion__pb2.QueryAnonimizacion.SerializeToString,
                response_deserializer=anonimizacion__pb2.RespuestaAnonimizacion.FromString,
                _registered_method=True)


class AnonimizacionServiceServicer(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    def CrearAnonimizacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAnonimizacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnonimizacionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearAnonimizacion': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearAnonimizacion,
                    request_deserializer=anonimizacion__pb2.Anonimizacion.FromString,
                    response_serializer=anonimizacion__pb2.RespuestaAnonimizacion.SerializeToString,
            ),
            'ConsultarAnonimizacion': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAnonimizacion,
                    request_deserializer=anonimizacion__pb2.QueryAnonimizacion.FromString,
                    response_serializer=anonimizacion__pb2.RespuestaAnonimizacion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'anonimizacion.AnonimizacionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('anonimizacion.AnonimizacionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnonimizacionService(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    @staticmethod
    def CrearAnonimizacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/anonimizacion.AnonimizacionService/CrearAnonimizacion',
            anonimizacion__pb2.Anonimizacion.SerializeToString,
            anonimizacion__pb2.RespuestaAnonimizacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAnonimizacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/anonimizacion.AnonimizacionService/ConsultarAnonimizacion',
            anonimizacion__pb2.QueryAnonimizacion.SerializeToString,
            anonimizacion__pb2.RespuestaAnonimizacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
